import { Component, Injectable } from '@angular/core';
import { FilmCategory } from '../film-category.enum';
import { Film } from '../film';

@Component({
  selector: 'app-fil-pojo',
  template: `
    <p>
      fil-pojo works!
    </p>
  `,
  styles: [
  ]
})

@Injectable({
  providedIn: 'root'
})

export class FilmPojoComponent {
  private films: Film[] = [
    {"Title":"Eternal Sunshine of the Spotless Mind","Year":"2004","Rated":"R","Released":"19 Mar 2004","Runtime":"108 min","Genre":"Drama, Romance, Sci-Fi","Director":"Michel Gondry","Writer":"Charlie Kaufman, Michel Gondry, Pierre Bismuth","Actors":"Jim Carrey, Kate Winslet, Tom Wilkinson","Plot":"When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories for ever.","Language":"English","Country":"United States","Awards":"Won 1 Oscar. 73 wins & 111 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"89/100"}],"Metascore":"89","imdbRating":"8.3","imdbVotes":"1,034,304","imdbID":"tt0338013","Type":"movie","DVD":"28 Sep 2004","BoxOffice":"$34,400,301","Production":"N/A","Website":"N/A","Response":"True"},
    { "Title": "Braveheart", "Year": "1995", "Rated": "R", "Released": "24 May 1995", "Runtime": "178 min", "Genre": "Biography, Drama, History", "Director": "Mel Gibson", "Writer": "Randall Wallace", "Actors": "Mel Gibson, Sophie Marceau, Patrick McGoohan", "Plot": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.", "Language": "English, French, Latin, Gaelic, Italian", "Country": "United States", "Awards": "Won 5 Oscars. 33 wins & 34 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.3/10" }, { "Source": "Rotten Tomatoes", "Value": "75%" }, { "Source": "Metacritic", "Value": "68/100" }], "Metascore": "68", "imdbRating": "8.3", "imdbVotes": "1,055,919", "imdbID": "tt0112573", "Type": "movie", "DVD": "19 Sep 2006", "BoxOffice": "$75,609,945", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "The Wind Rises", "Year": "2013", "Rated": "PG-13", "Released": "21 Feb 2014", "Runtime": "126 min", "Genre": "Animation, Biography, Drama", "Director": "Hayao Miyazaki", "Writer": "Hayao Miyazaki", "Actors": "Hideaki Anno, Hidetoshi Nishijima, Miori Takimoto", "Plot": "A look at the life of Jiro Horikoshi, the man who designed Japanese fighter planes during World War II.", "Language": "Japanese, German, Italian, French", "Country": "Japan", "Awards": "Nominated for 1 Oscar. 26 wins & 54 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTU4NDg0MzkzNV5BMl5BanBnXkFtZTgwODA3Mzc1MDE@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "88%" }, { "Source": "Metacritic", "Value": "83/100" }], "Metascore": "83", "imdbRating": "7.7", "imdbVotes": "90,409", "imdbID": "tt2013293", "Type": "movie", "DVD": "18 Nov 2014", "BoxOffice": "$5,209,580", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Full Metal Jacket", "Year": "1987", "Rated": "16+", "Released": "10 Jul 1987", "Runtime": "116 min", "Genre": "Drama, War", "Director": "Stanley Kubrick", "Writer": "Stanley Kubrick, Michael Herr, Gustav Hasford", "Actors": "Matthew Modine, R. Lee Ermey, Vincent D'Onofrio", "Plot": "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.", "Language": "English, Vietnamese", "Country": "United Kingdom, United States", "Awards": "Nominated for 1 Oscar. 8 wins & 15 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BNzkxODk0NjEtYjc4Mi00ZDI0LTgyYjEtYzc1NDkxY2YzYTgyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.3/10" }, { "Source": "Rotten Tomatoes", "Value": "91%" }, { "Source": "Metacritic", "Value": "78/100" }], "Metascore": "78", "imdbRating": "8.3", "imdbVotes": "759,371", "imdbID": "tt0093058", "Type": "movie", "DVD": "12 Jun 2001", "BoxOffice": "$46,357,676", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Porco Rosso", "Year": "1992", "Rated": "PG", "Released": "16 Dec 1994", "Runtime": "94 min", "Genre": "Animation, Adventure, Comedy", "Director": "Hayao Miyazaki", "Writer": "Hayao Miyazaki", "Actors": "Shûichirô Moriyama, Tokiko Katô, Bunshi Katsura Vi", "Plot": "In 1930s Italy, a veteran World War I pilot is cursed to look like an anthropomorphic pig.", "Language": "Japanese", "Country": "Japan", "Awards": "3 wins", "Poster": "https://m.media-amazon.com/images/M/MV5BNTZjMDc2N2UtZTdjZi00ODljLTgyZmEtNDljZDAwODY4NDVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "95%" }, { "Source": "Metacritic", "Value": "83/100" }], "Metascore": "83", "imdbRating": "7.7", "imdbVotes": "94,328", "imdbID": "tt0104652", "Type": "movie", "DVD": "03 Feb 2015", "BoxOffice": "$443,059", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Taxi", "Year": "1998", "Rated": "Not Rated", "Released": "20 Nov 1998", "Runtime": "89 min", "Genre": "Action, Comedy, Crime", "Director": "Gérard Pirès", "Writer": "Luc Besson", "Actors": "Samy Naceri, Frédéric Diefenthal, Marion Cotillard", "Plot": "To work off his tarnished driving record, a hip taxi driver must chauffeur a loser police inspector on the trail of German bank robbers.", "Language": "French, German, Korean, Portuguese", "Country": "France", "Awards": "3 wins & 5 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BODFmMWY3ZWQtMTBhNy00MzE4LWIxODYtNTFmMzczMzY1YmNjXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.0/10" }], "Metascore": "N/A", "imdbRating": "7.0", "imdbVotes": "86,312", "imdbID": "tt0152930", "Type": "movie", "DVD": "17 Nov 2003", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Memento Mori", "Year": "1999", "Rated": "R", "Released": "24 Dec 1999", "Runtime": "97 min", "Genre": "Horror, Romance, Drama", "Director": "Tae-yong Kim, Kyu-dong Min", "Writer": "Jung-Ok In, Tae-yong Kim, Kyu-dong Min", "Actors": "Gyu-ri Kim, Park Yejin, Yeong-jin Lee", "Plot": "In this second installment of the Whispering Corridors series, a young girl finds a strange diary, capable of arousing hallucinations, kept by two of her senior fellow-students who seem to have an unusually close bond.", "Language": "Korean", "Country": "South Korea", "Awards": "3 wins & 4 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BZGFhMGVkY2QtNTUxNy00NTdmLWE3ZDYtMjQyZWYxNzQwMzMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.3/10" }], "Metascore": "N/A", "imdbRating": "6.3", "imdbVotes": "3,520", "imdbID": "tt0266075", "Type": "movie", "DVD": "29 Apr 2014", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Lost in Translation", "Year": "2003", "Rated": "R", "Released": "03 Oct 2003", "Runtime": "102 min", "Genre": "Comedy, Drama", "Director": "Sofia Coppola", "Writer": "Sofia Coppola", "Actors": "Bill Murray, Scarlett Johansson, Giovanni Ribisi", "Plot": "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.", "Language": "English, Japanese, German, French", "Country": "United States, Japan", "Awards": "Won 1 Oscar. 98 wins & 134 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzk0NDg1MV5BMl5BanBnXkFtZTgwNDg0NjkxMDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "95%" }, { "Source": "Metacritic", "Value": "91/100" }], "Metascore": "91", "imdbRating": "7.7", "imdbVotes": "467,274", "imdbID": "tt0335266", "Type": "movie", "DVD": "03 Feb 2004", "BoxOffice": "$44,585,453", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Asteroid City", "Year": "2023", "Rated": "PG-13", "Released": "23 Jun 2023", "Runtime": "104 min", "Genre": "Comedy, Drama, Romance", "Director": "Wes Anderson", "Writer": "Wes Anderson, Roman Coppola", "Actors": "Jason Schwartzman, Scarlett Johansson, Tom Hanks", "Plot": "Following a writer on his world famous fictional play about a grieving father who travels with his tech-obsessed family to small rural Asteroid City to compete in a stargazing event, only to have his world view disrupted forever.", "Language": "English", "Country": "United States", "Awards": "1 nomination", "Poster": "https://m.media-amazon.com/images/M/MV5BNDJmMzY0ZGUtYWE1My00OWViLTg1NTctOWMwZWJlNDQzNGRiXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.0/10" }, { "Source": "Rotten Tomatoes", "Value": "82%" }, { "Source": "Metacritic", "Value": "74/100" }], "Metascore": "74", "imdbRating": "7.0", "imdbVotes": "5,476", "imdbID": "tt14230388", "Type": "movie", "DVD": "N/A", "BoxOffice": "$1,080,212", "Production": "N/A", "Website": "N/A", "Response": "True" },
    {"Title":"Eternal Sunshine of the Spotless Mind","Year":"2004","Rated":"R","Released":"19 Mar 2004","Runtime":"108 min","Genre":"Drama, Romance, Sci-Fi","Director":"Michel Gondry","Writer":"Charlie Kaufman, Michel Gondry, Pierre Bismuth","Actors":"Jim Carrey, Kate Winslet, Tom Wilkinson","Plot":"When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories for ever.","Language":"English","Country":"United States","Awards":"Won 1 Oscar. 73 wins & 111 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"89/100"}],"Metascore":"89","imdbRating":"8.3","imdbVotes":"1,034,304","imdbID":"tt0338013","Type":"movie","DVD":"28 Sep 2004","BoxOffice":"$34,400,301","Production":"N/A","Website":"N/A","Response":"True"},
    { "Title": "Braveheart", "Year": "1995", "Rated": "R", "Released": "24 May 1995", "Runtime": "178 min", "Genre": "Biography, Drama, History", "Director": "Mel Gibson", "Writer": "Randall Wallace", "Actors": "Mel Gibson, Sophie Marceau, Patrick McGoohan", "Plot": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.", "Language": "English, French, Latin, Gaelic, Italian", "Country": "United States", "Awards": "Won 5 Oscars. 33 wins & 34 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.3/10" }, { "Source": "Rotten Tomatoes", "Value": "75%" }, { "Source": "Metacritic", "Value": "68/100" }], "Metascore": "68", "imdbRating": "8.3", "imdbVotes": "1,055,919", "imdbID": "tt0112573", "Type": "movie", "DVD": "19 Sep 2006", "BoxOffice": "$75,609,945", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "The Wind Rises", "Year": "2013", "Rated": "PG-13", "Released": "21 Feb 2014", "Runtime": "126 min", "Genre": "Animation, Biography, Drama", "Director": "Hayao Miyazaki", "Writer": "Hayao Miyazaki", "Actors": "Hideaki Anno, Hidetoshi Nishijima, Miori Takimoto", "Plot": "A look at the life of Jiro Horikoshi, the man who designed Japanese fighter planes during World War II.", "Language": "Japanese, German, Italian, French", "Country": "Japan", "Awards": "Nominated for 1 Oscar. 26 wins & 54 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTU4NDg0MzkzNV5BMl5BanBnXkFtZTgwODA3Mzc1MDE@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "88%" }, { "Source": "Metacritic", "Value": "83/100" }], "Metascore": "83", "imdbRating": "7.7", "imdbVotes": "90,409", "imdbID": "tt2013293", "Type": "movie", "DVD": "18 Nov 2014", "BoxOffice": "$5,209,580", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Full Metal Jacket", "Year": "1987", "Rated": "16+", "Released": "10 Jul 1987", "Runtime": "116 min", "Genre": "Drama, War", "Director": "Stanley Kubrick", "Writer": "Stanley Kubrick, Michael Herr, Gustav Hasford", "Actors": "Matthew Modine, R. Lee Ermey, Vincent D'Onofrio", "Plot": "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.", "Language": "English, Vietnamese", "Country": "United Kingdom, United States", "Awards": "Nominated for 1 Oscar. 8 wins & 15 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BNzkxODk0NjEtYjc4Mi00ZDI0LTgyYjEtYzc1NDkxY2YzYTgyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.3/10" }, { "Source": "Rotten Tomatoes", "Value": "91%" }, { "Source": "Metacritic", "Value": "78/100" }], "Metascore": "78", "imdbRating": "8.3", "imdbVotes": "759,371", "imdbID": "tt0093058", "Type": "movie", "DVD": "12 Jun 2001", "BoxOffice": "$46,357,676", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Porco Rosso", "Year": "1992", "Rated": "PG", "Released": "16 Dec 1994", "Runtime": "94 min", "Genre": "Animation, Adventure, Comedy", "Director": "Hayao Miyazaki", "Writer": "Hayao Miyazaki", "Actors": "Shûichirô Moriyama, Tokiko Katô, Bunshi Katsura Vi", "Plot": "In 1930s Italy, a veteran World War I pilot is cursed to look like an anthropomorphic pig.", "Language": "Japanese", "Country": "Japan", "Awards": "3 wins", "Poster": "https://m.media-amazon.com/images/M/MV5BNTZjMDc2N2UtZTdjZi00ODljLTgyZmEtNDljZDAwODY4NDVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "95%" }, { "Source": "Metacritic", "Value": "83/100" }], "Metascore": "83", "imdbRating": "7.7", "imdbVotes": "94,328", "imdbID": "tt0104652", "Type": "movie", "DVD": "03 Feb 2015", "BoxOffice": "$443,059", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Memento Mori", "Year": "1999", "Rated": "R", "Released": "24 Dec 1999", "Runtime": "97 min", "Genre": "Horror, Romance, Drama", "Director": "Tae-yong Kim, Kyu-dong Min", "Writer": "Jung-Ok In, Tae-yong Kim, Kyu-dong Min", "Actors": "Gyu-ri Kim, Park Yejin, Yeong-jin Lee", "Plot": "In this second installment of the Whispering Corridors series, a young girl finds a strange diary, capable of arousing hallucinations, kept by two of her senior fellow-students who seem to have an unusually close bond.", "Language": "Korean", "Country": "South Korea", "Awards": "3 wins & 4 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BZGFhMGVkY2QtNTUxNy00NTdmLWE3ZDYtMjQyZWYxNzQwMzMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.3/10" }], "Metascore": "N/A", "imdbRating": "6.3", "imdbVotes": "3,520", "imdbID": "tt0266075", "Type": "movie", "DVD": "29 Apr 2014", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Lost in Translation", "Year": "2003", "Rated": "R", "Released": "03 Oct 2003", "Runtime": "102 min", "Genre": "Comedy, Drama", "Director": "Sofia Coppola", "Writer": "Sofia Coppola", "Actors": "Bill Murray, Scarlett Johansson, Giovanni Ribisi", "Plot": "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.", "Language": "English, Japanese, German, French", "Country": "United States, Japan", "Awards": "Won 1 Oscar. 98 wins & 134 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzk0NDg1MV5BMl5BanBnXkFtZTgwNDg0NjkxMDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "95%" }, { "Source": "Metacritic", "Value": "91/100" }], "Metascore": "91", "imdbRating": "7.7", "imdbVotes": "467,274", "imdbID": "tt0335266", "Type": "movie", "DVD": "03 Feb 2004", "BoxOffice": "$44,585,453", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Asteroid City", "Year": "2023", "Rated": "PG-13", "Released": "23 Jun 2023", "Runtime": "104 min", "Genre": "Comedy, Drama, Romance", "Director": "Wes Anderson", "Writer": "Wes Anderson, Roman Coppola", "Actors": "Jason Schwartzman, Scarlett Johansson, Tom Hanks", "Plot": "Following a writer on his world famous fictional play about a grieving father who travels with his tech-obsessed family to small rural Asteroid City to compete in a stargazing event, only to have his world view disrupted forever.", "Language": "English", "Country": "United States", "Awards": "1 nomination", "Poster": "https://m.media-amazon.com/images/M/MV5BNDJmMzY0ZGUtYWE1My00OWViLTg1NTctOWMwZWJlNDQzNGRiXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.0/10" }, { "Source": "Rotten Tomatoes", "Value": "82%" }, { "Source": "Metacritic", "Value": "74/100" }], "Metascore": "74", "imdbRating": "7.0", "imdbVotes": "5,476", "imdbID": "tt14230388", "Type": "movie", "DVD": "N/A", "BoxOffice": "$1,080,212", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title":"Eternal Sunshine of the Spotless Mind","Year":"2004","Rated":"R","Released":"19 Mar 2004","Runtime":"108 min","Genre":"Drama, Romance, Sci-Fi","Director":"Michel Gondry","Writer":"Charlie Kaufman, Michel Gondry, Pierre Bismuth","Actors":"Jim Carrey, Kate Winslet, Tom Wilkinson","Plot":"When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories for ever.","Language":"English","Country":"United States","Awards":"Won 1 Oscar. 73 wins & 111 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"89/100"}],"Metascore":"89","imdbRating":"8.3","imdbVotes":"1,034,304","imdbID":"tt0338013","Type":"movie","DVD":"28 Sep 2004","BoxOffice":"$34,400,301","Production":"N/A","Website":"N/A","Response":"True"},
    { "Title": "Braveheart", "Year": "1995", "Rated": "R", "Released": "24 May 1995", "Runtime": "178 min", "Genre": "Biography, Drama, History", "Director": "Mel Gibson", "Writer": "Randall Wallace", "Actors": "Mel Gibson, Sophie Marceau, Patrick McGoohan", "Plot": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.", "Language": "English, French, Latin, Gaelic, Italian", "Country": "United States", "Awards": "Won 5 Oscars. 33 wins & 34 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.3/10" }, { "Source": "Rotten Tomatoes", "Value": "75%" }, { "Source": "Metacritic", "Value": "68/100" }], "Metascore": "68", "imdbRating": "8.3", "imdbVotes": "1,055,919", "imdbID": "tt0112573", "Type": "movie", "DVD": "19 Sep 2006", "BoxOffice": "$75,609,945", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "The Wind Rises", "Year": "2013", "Rated": "PG-13", "Released": "21 Feb 2014", "Runtime": "126 min", "Genre": "Animation, Biography, Drama", "Director": "Hayao Miyazaki", "Writer": "Hayao Miyazaki", "Actors": "Hideaki Anno, Hidetoshi Nishijima, Miori Takimoto", "Plot": "A look at the life of Jiro Horikoshi, the man who designed Japanese fighter planes during World War II.", "Language": "Japanese, German, Italian, French", "Country": "Japan", "Awards": "Nominated for 1 Oscar. 26 wins & 54 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTU4NDg0MzkzNV5BMl5BanBnXkFtZTgwODA3Mzc1MDE@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "88%" }, { "Source": "Metacritic", "Value": "83/100" }], "Metascore": "83", "imdbRating": "7.7", "imdbVotes": "90,409", "imdbID": "tt2013293", "Type": "movie", "DVD": "18 Nov 2014", "BoxOffice": "$5,209,580", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Full Metal Jacket", "Year": "1987", "Rated": "16+", "Released": "10 Jul 1987", "Runtime": "116 min", "Genre": "Drama, War", "Director": "Stanley Kubrick", "Writer": "Stanley Kubrick, Michael Herr, Gustav Hasford", "Actors": "Matthew Modine, R. Lee Ermey, Vincent D'Onofrio", "Plot": "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.", "Language": "English, Vietnamese", "Country": "United Kingdom, United States", "Awards": "Nominated for 1 Oscar. 8 wins & 15 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BNzkxODk0NjEtYjc4Mi00ZDI0LTgyYjEtYzc1NDkxY2YzYTgyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.3/10" }, { "Source": "Rotten Tomatoes", "Value": "91%" }, { "Source": "Metacritic", "Value": "78/100" }], "Metascore": "78", "imdbRating": "8.3", "imdbVotes": "759,371", "imdbID": "tt0093058", "Type": "movie", "DVD": "12 Jun 2001", "BoxOffice": "$46,357,676", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Porco Rosso", "Year": "1992", "Rated": "PG", "Released": "16 Dec 1994", "Runtime": "94 min", "Genre": "Animation, Adventure, Comedy", "Director": "Hayao Miyazaki", "Writer": "Hayao Miyazaki", "Actors": "Shûichirô Moriyama, Tokiko Katô, Bunshi Katsura Vi", "Plot": "In 1930s Italy, a veteran World War I pilot is cursed to look like an anthropomorphic pig.", "Language": "Japanese", "Country": "Japan", "Awards": "3 wins", "Poster": "https://m.media-amazon.com/images/M/MV5BNTZjMDc2N2UtZTdjZi00ODljLTgyZmEtNDljZDAwODY4NDVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "95%" }, { "Source": "Metacritic", "Value": "83/100" }], "Metascore": "83", "imdbRating": "7.7", "imdbVotes": "94,328", "imdbID": "tt0104652", "Type": "movie", "DVD": "03 Feb 2015", "BoxOffice": "$443,059", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Memento Mori", "Year": "1999", "Rated": "R", "Released": "24 Dec 1999", "Runtime": "97 min", "Genre": "Horror, Romance, Drama", "Director": "Tae-yong Kim, Kyu-dong Min", "Writer": "Jung-Ok In, Tae-yong Kim, Kyu-dong Min", "Actors": "Gyu-ri Kim, Park Yejin, Yeong-jin Lee", "Plot": "In this second installment of the Whispering Corridors series, a young girl finds a strange diary, capable of arousing hallucinations, kept by two of her senior fellow-students who seem to have an unusually close bond.", "Language": "Korean", "Country": "South Korea", "Awards": "3 wins & 4 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BZGFhMGVkY2QtNTUxNy00NTdmLWE3ZDYtMjQyZWYxNzQwMzMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.3/10" }], "Metascore": "N/A", "imdbRating": "6.3", "imdbVotes": "3,520", "imdbID": "tt0266075", "Type": "movie", "DVD": "29 Apr 2014", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Lost in Translation", "Year": "2003", "Rated": "R", "Released": "03 Oct 2003", "Runtime": "102 min", "Genre": "Comedy, Drama", "Director": "Sofia Coppola", "Writer": "Sofia Coppola", "Actors": "Bill Murray, Scarlett Johansson, Giovanni Ribisi", "Plot": "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.", "Language": "English, Japanese, German, French", "Country": "United States, Japan", "Awards": "Won 1 Oscar. 98 wins & 134 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzk0NDg1MV5BMl5BanBnXkFtZTgwNDg0NjkxMDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }, { "Source": "Rotten Tomatoes", "Value": "95%" }, { "Source": "Metacritic", "Value": "91/100" }], "Metascore": "91", "imdbRating": "7.7", "imdbVotes": "467,274", "imdbID": "tt0335266", "Type": "movie", "DVD": "03 Feb 2004", "BoxOffice": "$44,585,453", "Production": "N/A", "Website": "N/A", "Response": "True" },
    { "Title": "Asteroid City", "Year": "2023", "Rated": "PG-13", "Released": "23 Jun 2023", "Runtime": "104 min", "Genre": "Comedy, Drama, Romance", "Director": "Wes Anderson", "Writer": "Wes Anderson, Roman Coppola", "Actors": "Jason Schwartzman, Scarlett Johansson, Tom Hanks", "Plot": "Following a writer on his world famous fictional play about a grieving father who travels with his tech-obsessed family to small rural Asteroid City to compete in a stargazing event, only to have his world view disrupted forever.", "Language": "English", "Country": "United States", "Awards": "1 nomination", "Poster": "https://m.media-amazon.com/images/M/MV5BNDJmMzY0ZGUtYWE1My00OWViLTg1NTctOWMwZWJlNDQzNGRiXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.0/10" }, { "Source": "Rotten Tomatoes", "Value": "82%" }, { "Source": "Metacritic", "Value": "74/100" }], "Metascore": "74", "imdbRating": "7.0", "imdbVotes": "5,476", "imdbID": "tt14230388", "Type": "movie", "DVD": "N/A", "BoxOffice": "$1,080,212", "Production": "N/A", "Website": "N/A", "Response": "True" }
  
  ];

  getFilms(): Film[] {
    return this.films;
  }

  getFilmSample(): Film[] {
    const max: number = Math.floor(Math.random() * (this.films.length - 1)) + 1;
    return this.films.slice(1, max);
  }
}
